name: kurani_fisnik_app
description: "Aplikacion Flutter për leximin dhe studimin e Kuranit Fisnik"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.2
  
  # Navigation
  go_router: ^14.2.7
  
  # Local Storage
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # HTTP Requests
  http: ^1.2.2
  
  # JSON Serialization
  json_annotation: ^4.9.0
  
  # Path utilities
  path_provider: ^2.1.4
  
  # Audio
  just_audio: ^0.10.4
  
  # File handling
  path: ^1.9.0
  
  # UI Components
  flutter_html: ^3.0.0-beta.2
  
  # Search functionality
  # fuzzywuzzy was unused; removed to slim dependencies
  
  # Rich text editor
  flutter_quill: ^11.4.2
  
  # Image handling
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  
  # Sharing
  share_plus: ^10.0.2
  
  # URL launcher
  url_launcher: ^6.3.1
  
  # Utilities
  uuid: ^4.4.0
  crypto: ^3.0.3

  # Permissions
  permission_handler: ^11.3.1
  
  # Notifications
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  
  # Icons
  cupertino_icons: ^1.0.8
  audio_session: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Testing dependencies
  mockito: ^5.4.4
  
  # Code generation
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
  - assets/data/
  # Ensure prebuilt search index is bundled explicitly (alongside the folder glob)
  - assets/data/search_index.json
  - assets/data/help/
  - assets/data/word/
  - assets/data/time/
  - assets/data/texhvid/
  - assets/fonts/
  - assets/images/
  # suret.json (emrat e sureve) përfshihet nga assets/data/ wildcard
  
  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
          weight: 400
    - family: AmiriQuran
      fonts:
        - asset: assets/fonts/AmiriQuran.ttf
          weight: 400
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lora-Bold.ttf
          weight: 700

